<?php

defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
require APPPATH . '/libraries/REST_Controller.php';

/**
 * This is an example of a few basic user interaction methods you could use
 * all done with a hardcoded array
 *
 * @package         CodeIgniter
 * @subpackage      Rest Server
 * @category        Controller
 * @author          Phil Sturgeon, Chris Kacerguis
 * @license         MIT
 * @link            https://github.com/chriskacerguis/codeigniter-restserver
 */
class News extends REST_Controller {

   function __construct()
    {
        // Construct the parent class
        parent::__construct();

        $this->load->library("Aauth");
		$this->load->model('survey_model');
		$this->load->model('user_model');
        $this->load->model('customer_model');
        $this->load->model('app_model');
        $this->load->model('event_model');
        $this->load->model('task_model');
    }


function get_news_post(){
    $requestjson = file_get_contents('php://input');
    $this->app_model->save_raw_data($requestjson);
    $requestjson = json_decode($requestjson, true);
   
        $token = $requestjson['token'];
       
        if ($token != '' && !empty($token)){
            $user_id = $this->user_model->get_user_from_token($token);
            
            if($user_id){
                
                $read_news = $this->event_model->get_read_news($user_id);
            
                $news = $this->event_model->get_unread_news($user_id); 
                $this->event_model->add_seen_news_event($user_id, $news->id);   
           
                $user_info = $this->aauth->get_user(); // remember this is an object not array.
                $data = $news;
				$message = [
				    'success' => true, // Automatically generated by the model
				    'data' => $data,
				    'message' => 'Successfully Retrieved'
				];

			}else{

				$message = [
				    'success' => false,
				    'data' => array(),
				    'message' => 'Please send an active token.'
				];
			}
		}else{

				$message = [
				    'success' => false,
				    'data' => array(),
				    'message' => 'Please send an active token.'
				];

		}
      
        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
        }
    
    }
        