<?php

defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
require APPPATH . '/libraries/REST_Controller.php';

/**
 * This is an example of a few basic user interaction methods you could use
 * all done with a hardcoded array
 *
 * @package         CodeIgniter
 * @subpackage      Rest Server
 * @category        Controller
 * @author          Phil Sturgeon, Chris Kacerguis
 * @license         MIT
 * @link            https://github.com/chriskacerguis/codeigniter-restserver
 */
class Taptuck extends REST_Controller {

    function __construct()
    {
        // Construct the parent class
        parent::__construct();

        $this->load->library("Aauth");
        $this->load->model('event_model');
        $this->load->model('app_model');
        $this->load->model('user_model');
        
        // Configure limits on our controller methods
        // Ensure you have created the 'limits' table and enabled 'limits' within application/config/rest.php
        $this->methods['user_get']['limit'] = 500; // 500 requests per hour per user/key
        $this->methods['user_post']['limit'] = 100; // 100 requests per hour per user/key
        $this->methods['user_delete']['limit'] = 50; // 50 requests per hour per user/key
    }

     public function transaction_notification_post()
    {
        $this->load->model('financial_model');
        $requestjson = file_get_contents('php://input');
        $this->app_model->save_raw_data($requestjson);
        $requestjson = json_decode($requestjson, true);

        if (isset($requestjson['key']) && $requestjson['key'] != '' && !empty($requestjson['key'])){
            
            if($requestjson['key'] == 'BB496112-C720-4706-9D41-640528F7AC9A'){

                    if(isset($requestjson['uuid']) && $requestjson['uuid'] != ''){

                        $this->financial_model->process_taptuck_transaction($requestjson['uuid']);

                        $message = [
                        'success' => true, // Automatically generated by the model
                        'data' => array(),
                        'message' => "OK"
                        ];

                    }else{

                        $message = [
                        'success' => false, // Automatically generated by the model
                        'data' => array(),
                        'message' => "Please supply a transaction uuid"
                        ];
                    }

            }else{
                $message = [
                'success' => false, // Automatically generated by the model
                'data' => array(),
                'message' => "Key not valid."
                ];
            }
        }else{

            $message = [
                'success' => false, // Automatically generated by the model
                'data' => array(),
                'message' => "Please post a valid key."
            ];
            
        }        

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }
}
