<?php

defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
require APPPATH . '/libraries/REST_Controller.php';

/**
 * This is an example of a few basic user interaction methods you could use
 * all done with a hardcoded array
 *
 * @package         CodeIgniter
 * @subpackage      Rest Server
 * @category        Controller
 * @author          Phil Sturgeon, Chris Kacerguis
 * @license         MIT
 * @link            https://github.com/chriskacerguis/codeigniter-restserver
 */
class Trader extends REST_Controller {

    function __construct()
    {
        // Construct the parent class
        parent::__construct();

        $this->load->library("Aauth");
		$this->load->model('pos_model');
        $this->load->model('event_model');
        $this->load->model('app_model');
        $this->load->model('financial_model');
        $this->load->model('user_model');
        $this->load->model('task_model');
        $this->load->model('airtime_model');
        $this->load->model('insurance_model');
    }

	public function get_trader_store_list_post()
    {

        $requestjson = file_get_contents('php://input');
        $requestjson = json_decode($requestjson, true);

        $this->app_model->save_raw_data(json_encode($requestjson));

        if (isset($requestjson['token']) && !empty($requestjson['token'] && $requestjson['token']) != ''){
          
            $this->load->model('user_model');
            $user_id = $this->user_model->get_user_from_token($requestjson['token']);

            $user_info = $this->user_model->get_user($user_id);
          
            $trader = $this->trader_model->get_trader($user_info->user_link_id);
            $data['stores'] = $trader;
        
            if(!empty($data)){
                
                $message = [
                    'success' => true, // Automatically generated by the model
                    'data' => $data,
                    'message' => 'Ok'
                ];
                

             }else{
                $message = [
                    'success' => false, // Automatically generated by the model
                    'data' => array(),
                    'message' => 'No trader found'
                ];
            }
        }else{
            $message = [
                'success' => false, // Automatically generated by the model
                'data' => array(),
                'message' => 'Please supply a valid token'
                ];
        }
        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }
    
}